# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(211D1B)
$foreground = rgb(F7EAD3)
$color0 = rgb(474441)
$color1 = rgb(7E5F72)
$color2 = rgb(A85946)
$color3 = rgb(857294)
$color4 = rgb(988146)
$color5 = rgb(AB884A)
$color6 = rgb(AE9261)
$color7 = rgb(EBD9B8)
$color8 = rgb(A49881)
$color9 = rgb(A87F98)
$color10 = rgb(DF765D)
$color11 = rgb(B298C5)
$color12 = rgb(CBAC5D)
$color13 = rgb(E3B562)
$color14 = rgb(E8C381)
$color15 = rgb(EBD9B8)
