# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171718)
$foreground = rgb(FCF7F5)
$color0 = rgb(3E3E3F)
$color1 = rgb(6966A3)
$color2 = rgb(A07A5A)
$color3 = rgb(838862)
$color4 = rgb(988346)
$color5 = rgb(8B8A9D)
$color6 = rgb(B9AFAA)
$color7 = rgb(F2EBE8)
$color8 = rgb(AAA5A3)
$color9 = rgb(8C88D9)
$color10 = rgb(D6A378)
$color11 = rgb(AFB682)
$color12 = rgb(CAAF5D)
$color13 = rgb(BAB8D2)
$color14 = rgb(F6E9E3)
$color15 = rgb(F2EBE8)
