# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(23222C)
$foreground = rgb(F6FBFD)
$color0 = rgb(494853)
$color1 = rgb(516382)
$color2 = rgb(5B7496)
$color3 = rgb(A3A6AD)
$color4 = rgb(ADAAB2)
$color5 = rgb(A2AFB9)
$color6 = rgb(ABB6BB)
$color7 = rgb(E9F0F4)
$color8 = rgb(A3A8AB)
$color9 = rgb(6C84AD)
$color10 = rgb(7A9BC8)
$color11 = rgb(DADDE6)
$color12 = rgb(E6E3ED)
$color13 = rgb(D9EAF6)
$color14 = rgb(E4F3FA)
$color15 = rgb(E9F0F4)
