-- Generated by nwg-displays on 2026-07-27 at 12:24:22. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x8A90",
    mode = "2880x1800@60.0",
    position = "0x1440",
    scale = 1.5
})
hl.monitor({
    output = "desc:Hisense Electric Co. Ltd. HISENSE 0x01010101",
    mode = "2560x1440@59.95",
    position = "1920x0",
    scale = 1.0
})
