-- Generated by nwg-displays on 2026-06-04 at 13:25:06. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x8A90",
    mode = "2880x1800@60.0",
    position = "0x0",
    scale = 1.5
})
hl.monitor({
    output = "desc:Seiko Epson Corporation EPSON PJ 0x01010101",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 2.0
})
