# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F9EECD
background         #040000
cursor             #CCA68F

active_tab_foreground     #040000
active_tab_background     #F9EECD
inactive_tab_foreground   #F9EECD
inactive_tab_background   #040000

active_border_color   #F9EECD
inactive_border_color #040000
bell_border_color     #322826

color0      #040000
color1		#322826
color2		#78463D
color3		#7C473D
color4		#7C473D
color5		#9C766E
color6		#B39A54
color7		#EEDEAF
color8		#A79B7A
color9		#423532
color10		#A05E51
color11		#A55E51
color12		#A55E51
color13		#D09E92
color14		#EECD70
color15		#EEDEAF
